name: 'dbt_production' #  project name
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project. Fivetran will use your connection settings defined in the UI, making this only relevant to local development.
profile: 'dbt_production'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_production:
    0_staging:
      +materialized: ephemeral
    1_intermediate:
      +materialized: view
      +schema: intermediate
    2_output:
      +pre-hook: "{{ my_schema_relations() }}"
      +materialized: table
      # +database: analytics_database


vars:
    ##Facebook Pages schema and database variables
    facebook_pages_schema: facebook_pages_schema

    ##Instagram Business schema and database variables
    instagram_business_schema: newinstagram_business_schema


    ##LinkedIn Pages schema and database variables
    linkedin_pages_schema: newlinkedin_company_pages_schema
